# Generated by Django 5.2.17 on 2026-10-06 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('npi', models.CharField(max_length=10)),
                ('type_acte', models.CharField(choices=[('ACTE_NAISSANCE', 'Acte de naissance'), ('CASIER_JUDICIAIRE', 'Casier judiciaire'), ('CERTIFICAT_RESIDENCE', 'Certificat de résidence')], max_length=30)),
                ('nombre_copies', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('DEPOSEE', 'Déposée'), ('EN_COURS', 'En cours de traitement'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='DEPOSEE', max_length=10)),
                ('motif_rejet', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, max_length=10, null=True)),
                ('nouveau_statut', models.CharField(max_length=10)),
                ('motif', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
