# Generated by Django 5.2.17 on 2026-10-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquestatut',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='demandes.demande'),
        ),
        migrations.AddIndex(
            model_name='demande',
            index=models.Index(fields=['npi', '-created_at'], name='demande_npi_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.CheckConstraint(condition=models.Q(('npi__length', 10)), name='demande_npi_length_10'),
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.CheckConstraint(condition=models.Q(('nombre_copies__gte', 1), ('nombre_copies__lte', 5)), name='demande_copies_1_5'),
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.CheckConstraint(condition=models.Q(('statut__in', ['DEPOSEE', 'EN_COURS', 'VALIDEE', 'REJETEE'])), name='demande_statut_valide'),
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.CheckConstraint(condition=models.Q(('type_acte__in', ['ACTE_NAISSANCE', 'CASIER_JUDICIAIRE', 'CERTIFICAT_RESIDENCE'])), name='demande_type_valide'),
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('statut', 'REJETEE'), _negated=True), models.Q(('motif_rejet', ''), _negated=True), _connector='OR'), name='demande_rejet_motive'),
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('created_by', 'idempotency_key'), name='demande_idempotency_unique'),
        ),
    ]
